// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_sta6wEcwnynCwU-PoWCCywBQJdnV1VY',
    appId: '1:541862121948:web:5f67b6a8899696e714ff19',
    messagingSenderId: '541862121948',
    projectId: 'farad-5bc61',
    authDomain: 'farad-5bc61.firebaseapp.com',
    storageBucket: 'farad-5bc61.firebasestorage.app',
    measurementId: 'G-E2NCYPPT1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi39QxU67_1B76KgaWKKEJ6GW_2Vj_UtQ',
    appId: '1:541862121948:android:9c931e260c37e49914ff19',
    messagingSenderId: '541862121948',
    projectId: 'farad-5bc61',
    storageBucket: 'farad-5bc61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFKfgPOVHuZcnpgNC-SIpnv2xcVJUwoCo',
    appId: '1:541862121948:ios:e3a24c895c14fb0d14ff19',
    messagingSenderId: '541862121948',
    projectId: 'farad-5bc61',
    storageBucket: 'farad-5bc61.firebasestorage.app',
    iosBundleId: 'com.example.farad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFKfgPOVHuZcnpgNC-SIpnv2xcVJUwoCo',
    appId: '1:541862121948:ios:e3a24c895c14fb0d14ff19',
    messagingSenderId: '541862121948',
    projectId: 'farad-5bc61',
    storageBucket: 'farad-5bc61.firebasestorage.app',
    iosBundleId: 'com.example.farad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_sta6wEcwnynCwU-PoWCCywBQJdnV1VY',
    appId: '1:541862121948:web:0a4c5d3ecfab8ecb14ff19',
    messagingSenderId: '541862121948',
    projectId: 'farad-5bc61',
    authDomain: 'farad-5bc61.firebaseapp.com',
    storageBucket: 'farad-5bc61.firebasestorage.app',
    measurementId: 'G-31EMYYERM5',
  );
}
